[build]
  command = "npm run build"
  publish = "dist"

# Force SPA-style routing to index.html (safe even if not using client-side routes)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Sensible security headers (can tweak as needed)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"